name: Continuous Integration

on: [push, pull_request]

jobs:
  build_and_test:
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:10.12-alpine
        env:
          POSTGRES_USER: test
          POSTGRES_PASSWORD: test
          POSTGRES_DB: pongstars
        ports:
          - 5432:5432
        # needed because the postgres container does not provide a healthcheck
        options: --health-cmd pg_isready --health-interval 10s --health-timeout 5s --health-retries 5

    steps:
      - uses: actions/checkout@v2
      - name: ⚡ Cache
        uses: actions/cache@v2
        with:
          path: |
            ~/.cargo/registry
            ~/.cargo/git
            target
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}

      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable

      - name: 🔨 Build
        uses: actions-rs/cargo@v1
        with:
          command: build

      - name: Create env file
        run: mv .env.example .env

      - name: 🔎 Unit test
        uses: actions-rs/cargo@v1
        with:
          command: test

      - name: ⚙ Integration test
        uses: actions-rs/cargo@v1
        with:
          command: test
          args: --features "integration_tests"
    # - name: Run migrations
    #   run: sqlx migration run
    #   env:
    #     DATABASE_URL: postgres://test:test@postgres:5432/pongstars
